version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Build and test
          # TODO: Set up a Dockerfile for this.
          command: |
            apt-get update
            apt-get install -y \
              git \
              clang \
              python \
              libprotobuf-dev \
              libcurl4-nss-dev \
              libsdl2-dev \
              libsdl2-ttf-dev \
              libsdl2-image-dev \
              libmicrohttpd-dev \
              libffms2-dev \
              libusb-1.0-0-dev
            git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
            ./build/ci.sh
