version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Build and test
          # TODO: Set up a Dockerfile for this.
          # TODO: Check in unit-test specific files in this repository
          command: |
            apt-get update
            apt-get install -y \
              git clang cmake ninja-build \
              libgoogle-glog-dev libgflags-dev libprotobuf-dev \
              libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev \
              libmicrohttpd-dev libffms2-dev libusb-1.0-0-dev
            git submodule init
            git submodule sync
            ./build/travis.sh
