version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Setup environment
          # TODO: Set up a Dockerfile for this.
          command: |
            apt-get update
            apt-get install -y \
              git \
              clang \
              python \
              libprotobuf-dev \
              libcurl4-nss-dev \
              libsdl2-dev \
              libsdl2-ttf-dev \
              libsdl2-image-dev \
              libmicrohttpd-dev \
              libffms2-dev \
              libusb-1.0-0-dev
            git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
            pwd
            ls
      - run:
          name: Checkout
          command: |
            echo 'export PATH=~/depot_tools:$PATH' >> $BASH_ENV
            source $BASH_ENV
            gclient config --spec 'solutions = [{ "url": "https://github.com/puyoai/puyoai.git", "managed": False, "name": "puyoai", "deps_file": "DEPS", "custom_deps": { "test_resources": None }}]'
            gclient sync
      - run:
          name: Build
          working_directory: ~/puyoai
          command: |
            source $BASH_ENV
            ./build/ci.sh
      - run:
          name: Run rests
          working_directory: ~/puyoai
          command: |
            source $BASH_ENV
            ./build/run_unittest.py
