version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            apt-get install -y \
              git clang cmake ninja-build \
              libgoogle-glog-dev libgflags-dev libprotobuf-dev \
              libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev \
              libmicrohttpd-dev libffms2-dev libusb-1.0-0-dev
            ./build/travis.sh
